version: "3.3"
   
services:
  postgres:
    image: postgres:12
    env_file:
      - './infrastucture/services/postgres/.env'
  django:
    build: ./backend
    command: "gunicorn backend.wsgi --bind 0.0.0.0:8001"
    volumes:
      - ./backend:/app/api
      - static_volume:/static
      - media_volume:/media
    env_file:
      - './infrastucture/services/postgres/.env'
      - './infrastucture/apps/backend/.env'
    expose:
      - 8001
    depends_on:
      - postgres
  