# Generated by Django 4.1.1 on 2022-10-17 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Intern', 'Стажировка'), ('Vacancy', 'Вакансия')], default='Intern', max_length=11)),
                ('title', models.TextField(verbose_name='Название вакансии/стажировки')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Текст вакансии')),
            ],
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='ФИО')),
                ('email', models.TextField(verbose_name='Почта')),
                ('phone', models.TextField(verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.application')),
            ],
        ),
    ]
