# Generated by Django 4.1.1 on 2022-10-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Client', 'Клиент'), ('Partner', 'Партнер')], default='Client', max_length=11)),
                ('full_name', models.TextField(verbose_name='ФИО')),
                ('phone', models.TextField(verbose_name='Телефон')),
                ('company', models.TextField(verbose_name='Название компании')),
                ('email', models.TextField(verbose_name='Электронная почта')),
                ('budget', models.CharField(choices=[('<1', 'До 1 млн рублей'), ('1:3', 'от 1 до 3 млн рублей'), ('3:5', 'от 3 до 5 млн рублей'), ('5:10', 'от 5 до 10 млн рублей'), ('>10', 'от 10 млн рублей')], default='<1', max_length=11)),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
        ),
    ]
