# Generated by Django 4.1.1 on 2022-10-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='budget',
            field=models.CharField(blank=True, choices=[('<1', 'до 1 млн рублей'), ('1:3', 'от 1 до 3 млн рублей'), ('3:5', 'от 3 до 5 млн рублей'), ('5:10', 'от 5 до 10 млн рублей'), ('>10', 'от 10 млн рублей')], default='<1', max_length=11),
        ),
    ]
